-- CALENDAR 테이블
CREATE TABLE CALENDAR (
    CALENDAR_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    YEAR INTEGER,
    MONTH INTEGER,
    DAY INTEGER,
    WEEK VARCHAR(3),
    HOLIDAY_YN VARCHAR(2),
    HOLIDAY_NAME VARCHAR(50),
    DT DATE
);

-- BOARD 테이블
CREATE TABLE BOARD (
    BOARD_ID VARCHAR(200) PRIMARY KEY,
    USER_ID VARCHAR(50),
    DT DATE
);

-- PLAN 테이블
CREATE TABLE PLAN (
    PLAN_ID VARCHAR(200) PRIMARY KEY,
    BOARD_ID VARCHAR(200),
    TITLE VARCHAR(200),
    COMMIT_CHK VARCHAR(1),
    CONTENT VARCHAR(500),
    BACK_COLOR VARCHAR(100),
    STRT_DT DATE,
    END_DT DATE
);